services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cineclub
    ports:
      - "5432:5432"  
    volumes:
      - cineclub_backend:/var/lib/postgresql/data

volumes:
  cineclub_backend: {}
