server:
  port: ${SERVER_PORT}

# application:
  # security:
    # jwt:
      # secret-key: ${JWT_SECRET_KEY}
      # expiration: 86400000 # 1 day
      # refresh-token:
       # expiration: 604800000 # 7 days
spring:
  application:
    name: CineClub Backend

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
